name: mivi
description: "A modern Flutter movie app with a beautiful UI and scalable architecture."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^12.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  youtube_player_flutter: ^8.1.2
  # API dependencies
  http: ^1.1.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  supabase_flutter: ^2.9.1
  video_player: ^2.8.1
  # AI dependencies
  google_generative_ai: ^0.2.2
  flutter_animate: ^4.5.0
  bubble: ^1.2.1
  # Wit.ai (uses http for API calls)
  # No specific package needed, we'll use http directly
  # Notifications
  flutter_local_notifications: ^17.2.3
  # Web push notifications (Firebase alternative)
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.4
  # Voice search
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.0
  # Text to Speech
  flutter_tts: ^4.0.2
  # Audio Player
  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  # API dev dependencies
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
